displayName=Ocean Encounter Stats
author=Blonks
description=An example greeter plugin
tags=ocean,encounter,stats,sailing,boat
version=1.0.0
plugins=dev.blonks.osrs.oceanencounters.OceanEncounterPlugin
build=standard